apiVersion: 1
contactPoints:
  - name: Discord
    receivers:
      - uid: discord-webhook
        type: discord
        settings:
          url: $__env{ALERT_WEBHOOK_URL}
          message: "{{ template \"discord.embed\" . }}"
        disableResolveMessage: false
